name: Full CI-CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8
        ports:
          - "3306:3306"
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: my_db
        options: >-
          --health-cmd="mysqladmin ping -h localhost -proot"
          --health-interval=5s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup-node
        uses: actions/setup-node@v4
        with:
          node-version: 18
          
      - name: Install backend dependencies
        working-directory: ./backend
        run: npm install

      - name: Setup MySql Client
        run: sudo apt-get update && sudo apt-get install mysql-client

      - name: Wait for MySql
        run: |
          for i in {1..10};do
            mysqladmin ping -h 127.0.0.1 -proot && break
            echo "waiting for mysql"
            sleep 3
          done

      - name: Run backend
        working-directory: ./backend
        env:
          DB_HOST: 127.0.0.1
          DB_USER: root
          DB_PASSWORD: root
          DB_NAME: my_db
        run: |
          node app.js &
          sleep 5

      - name: Test API
        run: |
          curl -f http://localhost:5000/api/data

  build-and-push:
    needs: test
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout-code
        uses: actions/checkout@v4

      - name: Build frontend
        working-directory: ./frontend
        run: docker build -t ghcr.io/${{secrets.GITH_USERNAME}}/frontend:1.0 .

      - name: Build backend
        working-directory: ./backend
        run: docker build -t ghcr.io/${{secrets.GITH_USERNAME}}/backend:1.0 .

      - name: GHCR login
        run: echo ${{secrets.GITH_TOKEN}} | docker login ghcr.io -u ${{secrets.GITH_USERNAME}} --password-stdin

      - name: Backend image push
        run: docker push ghcr.io/sreevishnu07/backend:1.0

      - name: Frontend image push
        run: docker push ghcr.io/sreevishnu07/frontend:1.0
      
          
          
            
          
      

      
      
